AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template is partially managed by Amazon.Lambda.Annotations (v1.3.0.0).
Parameters:
  ACMCertificateArn:
    Type: String
    Description: ARN of the ACM certificate for ltly.me
Resources:
  LtlyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
        - http://localhost:5173
        AllowHeaders:
        - authorization
        - content-type
        - host
        AllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        MaxAge: 600
        AllowCredentials: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
    Metadata:
      SamResourceId: LtlyApi
  LtlyDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: ltly.link
      DomainNameConfigurations:
      - CertificateArn:
          Ref: ACMCertificateArn
        EndpointType: REGIONAL
    Metadata:
      SamResourceId: LtlyDomain
  LtlyApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId:
        Ref: LtlyApi
      DomainName:
        Ref: LtlyDomain
      Stage: $default
    Metadata:
      SamResourceId: LtlyApiMapping
  LtlyDefaultLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LtlyDefaultLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/CloudWatchFullAccessV2
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      - arn:aws:iam::aws:policy/AWSLambda_FullAccess
    Metadata:
      SamResourceId: LtlyDefaultLambdaRole
  ShortenUrl:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ShortenUrl
      SyncedEvents:
      - RootPost
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: ShortenUrl
      Runtime: dotnet8
      CodeUri: s3://ltly-default/c8d04bdcfb8b7447f07f3623d1b99dd1
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Fn::GetAtt:
        - LtlyDefaultLambdaRole
        - Arn
      PackageType: Zip
      Handler: Ltly.Lambda::Ltly.Lambda.Functions.UrlShortenerFunctions_ShortenUrl_Generated::ShortenUrl
      Events:
        RootPost:
          Type: HttpApi
          Properties:
            Path: /api/v1/shorten
            Method: POST
            ApiId:
              Ref: LtlyApi
  Redirect:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Redirect
      SyncedEvents:
      - RootGet
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: Redirect
      Runtime: dotnet8
      CodeUri: s3://ltly-default/c8d04bdcfb8b7447f07f3623d1b99dd1
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Fn::GetAtt:
        - LtlyDefaultLambdaRole
        - Arn
      PackageType: Zip
      Handler: Ltly.Lambda::Ltly.Lambda.Functions.UrlShortenerFunctions_Redirect_Generated::Redirect
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /{token}
            Method: GET
            ApiId:
              Ref: LtlyApi
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${LtlyDomain}
