AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template is partially managed by Amazon.Lambda.Annotations (v1.3.0.0).
Resources:
  LtlyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: ltly
      CorsConfiguration:
        AllowOrigins:
        - https://localhost:5173
        - https://ltly.dbrdak.com
        AllowHeaders:
        - authorization
        - content-type
        - host
        AllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        MaxAge: 600
        AllowCredentials: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
    Metadata:
      SamResourceId: LtlyApi
  LtlyDefaultLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LtlyDefaultLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/CloudWatchFullAccessV2
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      - arn:aws:iam::aws:policy/AWSLambda_FullAccess
    Metadata:
      SamResourceId: LtlyDefaultLambdaRole
  ShortenUrl:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ShortenUrl
      SyncedEvents:
      - RootPost
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: ShortenUrl
      Runtime: dotnet8
      CodeUri: s3://ltly-default/3523b366f1b34008055e8340e1e1b1e0
      MemorySize: 3008
      Timeout: 30
      Role:
        Fn::GetAtt:
        - LtlyDefaultLambdaRole
        - Arn
      PackageType: Zip
      Handler: Ltly.Lambda::Ltly.Lambda.Functions.UrlShortenerFunctions_ShortenUrl_Generated::ShortenUrl
      Events:
        RootPost:
          Type: HttpApi
          Properties:
            Path: /s
            Method: POST
            ApiId:
              Ref: LtlyApi
  Redirect:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Redirect
      SyncedEvents:
      - RootGet
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: Redirect
      Runtime: dotnet8
      CodeUri: s3://ltly-default/3523b366f1b34008055e8340e1e1b1e0
      MemorySize: 3008
      Timeout: 30
      Role:
        Fn::GetAtt:
        - LtlyDefaultLambdaRole
        - Arn
      PackageType: Zip
      Handler: Ltly.Lambda::Ltly.Lambda.Functions.UrlShortenerFunctions_Redirect_Generated::Redirect
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /s/{token}
            Method: GET
            ApiId:
              Ref: LtlyApi
  RemoveOldUrls:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: RemoveOldUrls
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName: RemoveOldUrls
      Runtime: dotnet8
      CodeUri: s3://ltly-default/3523b366f1b34008055e8340e1e1b1e0
      MemorySize: 3008
      Timeout: 30
      Role:
        Fn::GetAtt:
        - LtlyDefaultLambdaRole
        - Arn
      PackageType: Zip
      Handler: Ltly.Lambda::Ltly.Lambda.Functions.UrlShortenerFunctions_RemoveOldUrls_Generated::RemoveOldUrls
      Events:
        RemoveOldUrlsEvent:
          Type: Schedule
          Properties:
            Name: RemoveOldUrls
            Schedule: rate(1 day)
