AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This template is partially managed by Amazon.Lambda.Annotations (v1.3.0.0).
Resources:
  LtlyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:5173"
        AllowHeaders:
          - authorization
          - content-type
          - host
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        MaxAge: 600
        AllowCredentials: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
  LtlyDefaultLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LtlyDefaultLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccessV2
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
  ShortenUrl:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 3008
      Timeout: 30
      Role: !GetAtt LtlyDefaultLambdaRole.Arn
      PackageType: Zip
      Handler: Ltly.Lambda::Ltly.Lambda.Functions.UrlShortenerFunctions_ShortenUrl_Generated::ShortenUrl
      Events:
        RootPost:
          Type: HttpApi
          Properties:
            Path: /s
            Method: POST
  Redirect:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootGet
    Properties:
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 3008
      Timeout: 30
      Role: !GetAtt LtlyDefaultLambdaRole.Arn
      PackageType: Zip
      Handler: Ltly.Lambda::Ltly.Lambda.Functions.UrlShortenerFunctions_Redirect_Generated::Redirect
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /s/{token}
            Method: GET
  RemoveOldUrls:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 3008
      Timeout: 30
      Role: !GetAtt LtlyDefaultLambdaRole.Arn
      PackageType: Zip
      Handler: Ltly.Lambda::Ltly.Lambda.Functions.UrlShortenerFunctions_RemoveOldUrls_Generated::RemoveOldUrls
      Events:
        RemoveOldUrlsEvent:
          Type: Schedule
          Properties:
            Name: RemoveOldUrls
            Schedule: rate(1 day)
