# name: Deploy to Chrome Web Store

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Zip Extension
#         run: |
#           echo "Creating extension.zip from Ltly.Plugin directory"
#           cd Ltly.Plugin
#           zip -r ../Ltly.Plugin.zip . -x '*.git*' -x 'node_modules/**'
#           cd ..

#       - name: Publish to Chrome Web Store
#         uses: w9jds/publish-chrome-extension@v3.2.0
#         with:
#           extensionId: ${{ secrets.EXTENSION_ID }}
#           clientId: ${{ secrets.CLIENT_ID }}
#           clientSecret: ${{ secrets.CLIENT_SECRET }}
#           refreshToken: ${{ secrets.REFRESH_TOKEN }}
#           asset: extension.zip
#           publish: true
